### ISSUE TITLE
Documentation: how to use this?

### ISSUE THREAD

**Issue by jargv** [ninenines/live#2]
I'm new to erlang, but can already see how something like this could greatly improve workflow. Unfortunately I'm not adept enough with erlang to figure out usage from code directly. Just a bit of docs would be great. Alternatively, if I can get it working, I'd be happy to contribute some docs/examples, though I'll probably need to be pointed in the right direction.

**Comment by essen** [comment]
Depends on what you need to do. This project monitors files and triggers callbacks when they change. It was created to easily detect configuration file changes and reload them (for example with an SDL application, configuration file changes, resize the window automatically). By default it of course comes with BEAM file reloading, but that can be disabled also.

**Comment by essen** [comment]
Closing, hope you had enough to go on. I unfortunately have basically no time to devote on this (and on the project I use it for) so this will have to wait, sorry.
